### ISSUE TITLE
Fuzzy Search for Countries to add to speakers list is not very precise and sometimes confusing

### ISSUE THREAD

**Issue by TadeSF** [DeutscheModelUnitedNations/munify-chase#177]
ist etwas anstrengen das immer die Länder vorgeschlagen die am wenigsten zur eingabe Passen (zB. bei Ch wird Schweiz, Frankreich und die Welthungerhilfe vorgeschlagen)

**Comment by TadeSF** [comment]
@JEval42 do you want to tackel this issue? Then ill assign you ;)

**Comment by JEval42** [comment]
Let's do it :)

**Comment by TadeSF** [comment]
Do you want me to onboard you quickly on the issue or do you know where to look? 😊

**Comment by JEval42** [comment]
I had a look now and I am wondering, how we would like to change it. The example above does not seem confusing to me since Ch indeed appears in sCHweiz , frankreiCH, and deutsCHe hungerhilfe. I suspect that someone wanted to get China or Chile, but was in a wrong council which did not have these countries as members. 
If I understand it correctly, fuse is only looking for these matches of strings. It does not take into account more advanced stuff like whether a wrong letter is close to a correct letter on a keyboard.  Things we could easily change are the following:

- Increase the minMatchCharLength from 1 to 2. Then, single character matches will not show up
- Reduce the distance in which he looks for a match. Right now he looks for matches in the first 60 characters. In our case, this means everywhere. We could reduce this, but I think this is quite dangerous: Being too strict would mean that "Deutsche Umwelthilfe" does not show up if someone types "umwelthilfe".
- Changing the keys where he looks. Right now, he searches for matches in the country name. It looks like it is supposed that he also looks at the alph3code, but this is currently not active because of a bug,
- Making the search case sensitive. This seems like a terrible idea...

**Comment by TadeSF** [comment]
Nice! Thanks for the research.
From my point of view, I would suggest to change the minMatchCharLength to two or even three. Maybe you can test a little bit what feels natural?

I agree that making search case sensitive is a terrible Idea. I also agree that we should not restrict the distance for the reason you described.

The alpha3code match is disabled because there were complaints about weird and unhelpful matches when countries have different names in english (hence the alpha3code is very different to the german word) – thats why I disabled it and I would keep it that way.

@m1212e any additional thoughts on this?

Just an Idea: It might be useful to research for a more capable alternative to this fuzzy package?

**Comment by m1212e** [comment]
Yeah we could look for a fuse alternative. Also: Can we maybe weigh the Order of appearance in the found string more the further they are at the start (of each word)? So a match for "CH" in "sCHweiz" will rank higher than in "vereinigte arabisCHe Emirate"? This would strengthen results following the natural behavior of typing the starting letters when searching.

**Comment by TadeSF** [comment]
Without doing something totally insane for that usecase like using elasticsearch, I think we don't really have any really better alternatives to fuse.js. What I found were these libraries: [fuzzy](https://www.npmjs.com/package/fuzzy) and [lunr](https://www.npmjs.com/package/lunr). But both don't look more promising then fuse already looks.

Sorting is a very good Idea. @JEval42 since you have read into this – do you think configuring it like that would be easy to implement?

I would suggest then that we go with a higher minMatchCharLength and sorting like @m1212e suggested if possible.

**Comment by JEval42** [comment]
Sorry for the long pause. I looked into it and it seems that it already considers how early the match occurs. However, it also prefers short strings over long strings. That is why typing "V" will cause "Malediven" to be ranked higher than "Vereinigtes Königreich". I suggest to enable "ignoreFieldNorm" which tells fusy to ignore the length of the strings. Then, "V" will yield "Vereinigte Arabische Emirate", "Vereinigtes Königreich", "Vereinigte Republik Tansania"
Personally, I would not increase minMatchCharLength. It gives chairs the chance to realise that certain countries can be accessed by typing only one letter. 
Another feature could be that when nothing has been typed, the four most active countries are suggested.

**Comment by TadeSF** [comment]
No worries. Thanks for your insights! I would second your suggestion to enable "ignoreFieldNorm" then. Please open a Pull Request to main once you are ready.

To your last feature suggestion: Is that something you stumbled across that makes implementing it easy? Or is that just a general thought of yours?

**Comment by JEval42** [comment]
The last feature suggestion was just a general thought.
